name       : python-fann2
version    : 1.1.2
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/f/fann2/fann2-1.1.2.tar.gz : cdca0a65ad48e08320672affe38c3dd4ea15e27821e5e1db9fa2b34299bdd41e
license    : Apache-2.0
component  : programming.python
summary    : Python bindings for Fast Artificial Neural Networks 2.2.0
description: |
    This is a python binding for Fast Artificial Neural Network Library (FANN >= 2.2.0) that implements multi-layer artificial neural networks with support for both fully-connected and sparsely-connected networks. It includes a framework for easily handling training data sets. It is easy to use, versatile, well- documented, and fast.
builddeps  :
    - pkgconfig(fann)
    - pkgconfig(python3)
    - swig
build      : |
    %python3_setup
install    : |
    %python3_install
