name       : python-fann2
version    : 1.0.7
release    : 1
source     :
    - https://files.pythonhosted.org/packages/a9/a3/af368a683a04850aa1bf2e097f17781eb26e7e7c269ddcecfcec5f2e05a3/fann2-1.0.7.tar.gz : 53eca74a2c0a0dfcf2d8e449cf487603886dadeda343adab4c0f1b811734fb9f
license    : Apache-2.0
component  : programming.python
summary    : Python bindings for Fast Artificial Neural Networks 2.2.0
description: |
    This is a python binding for Fast Artificial Neural Network Library (FANN >= 2.2.0) that implements multi-layer artificial neural networks with support for both fully-connected and sparsely-connected networks. It includes a framework for easily handling training data sets. It is easy to use, versatile, well- documented, and fast.
builddeps  :
    - pkgconfig(fann)
    - pkgconfig(python3)
    - swig
build      : |
    %python3_setup
install    : |
    %python3_install
